make:
	go run main.go

update:
	cd .. && git fetch && git pull && cd Camion_Files

create:
	touch registry_truck_pyme_1.csv && touch registry_truck_retail_1.csv && touch registry_truck_retail_2.csv

clean:
	rm *.csv